### ISSUE TITLE
As a user of youb_sustainable’s services I want to be able to login to my account so I can see my dashboard page and use the site.

### ISSUE THREAD

**Issue by lisakanbur** [UB-CSE/course-project-yo-ub_sustainable#41]
Acceptance Tests:
1. Navigate to youb_sustainable’s website at  https://youbsustainable.herokuapp.com/.
2. Site viewer should see you_sustainable’s homepage.
3. Site viewer can click on log in on the homepage and they will be redirected to the log in page.
4. Enter the necessary information into the fields displayed on the page.
5. Site viewer can click on the log in button on the log in page and will be redirected to their personal dashboard.
6. Personal dashboard should display current challenges.

**Comment by JQuelen** [comment]
Do you have an example account that the grader can use to login?

**Comment by lisakanbur** [comment]
Example account credentials:
Username: test
Password: test
