### ISSUE TITLE
As a person who wants to complete more sustainability challenges I want to be able to view all the different challenges So that I can work on my sustainable lifestyle

### ISSUE THREAD

**Issue by urjithamuthiah** [UB-CSE/course-project-yo-ub_sustainable#42]
Acceptance Test:

- Site viewer can click on challenges on the home page 
- Site viewer will be redirected to a new page
- Site viewer can view a list of challenges on this new page in a table format
- Site viewer can click on a specific challenge with corresponding "Details" button
- Site viewer should be redirected to the specific challenge page
- Site viewer should be able to view all details about the specific challenge like challenge title, summary and helpful suggestions, image etc.
- Site viewer can see that the Challenge Name on the redirected page is the same as the one from the table for which they clicked "Details" button

**Comment by JQuelen** [comment]
This is really good, keep it up!
