### ISSUE TITLE
As a person navigating the website I want to use a site-wide navbar So I can easily access different pages in the web app

### ISSUE THREAD

**Issue by bennyloo** [UB-CSE/course-project-yo-ub_sustainable#43]
Acceptance Test:
1. The user sees a navbar at the top of any page they are on
2. If user clicks on a link in the navbar, they should be redirected to that page
Ex: Clicking on friends on the navbar will take user to friends page
3. If the user is logged in, they should see a sign out button instead of a login button
4. If the user is logged in, clicking on the sign out button will sign them out
5. User should see the current page they are currently on highlighted in the navbar (except for login/signup)
6. If user clicks on the link to the current page in the navbar, the page should not refresh
7. If user clicks on the logo, the webapp should redirect to the home page. If the user is currently on the homepage, clicking on the logo should not refresh the page.

**Comment by JQuelen** [comment]
Really good User Stories and Acceptance Tests here
