### ISSUE TITLE
Replace Navbar Log In Button with Log Out button when User is Logged In

### ISSUE THREAD

**Issue by bennyloo** [UB-CSE/course-project-yo-ub_sustainable#50]
Task Test

- Login Button is visible and can be clicked on in all pages except login/signup.html when not logged in
- Login Button is replaced with Log Out button when user is logged in.
- Clicking on Log Out button logs out user.
- When user is logged out, Login Button replaces Log Out Button in all pages except login/signup.

**Comment by bennyloo** [comment]
Task Test

- Login Button is visible and can be clicked on in all pages except login/signup.html when not logged in
- Login Button is replaced with Log Out button when user is logged in.
- Clicking on Log Out button logs out user.
- When user is logged out, Login Button replaces Log Out Button in all pages except login/signup.

**Comment by JQuelen** [comment]
The Task Test is really good here! Is there any way the grader can log in to an account so that they can see the login/logout button change?
